
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 09 18:46:00 COT 2015
//----------------------------------------------------

package convertidor;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int atributo = 6;
  public static final int simbolo = 9;
  public static final int java = 4;
  public static final int programacion = 5;
  public static final int variable = 11;
  public static final int herencia = 8;
  public static final int lenguaje = 7;
  public static final int CONVERTIR = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int codigo = 10;
  public static final int clase = 2;
  public static final int metodo = 3;
}

